BEGIN;
DROP TABLE IF EXISTS users,posts, comments, votes CASCADE;
CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    username VARCHAR(30) NOT NULL UNIQUE,
    email VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE posts(
    id SERIAL PRIMARY KEY,
    title VARCHAR(50) NOT NULL ,
  content TEXT NOT NULL ,
  image_url VARCHAR(50) NOT NULL ,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  userId INTEGER NOT NULL,
  CONSTRAINT fk_userId FOREIGN KEY (userId) REFERENCES users(id)
 
);
CREATE TABLE votes (
    id INTEGER PRIMARY KEY ,
    voteType TEXT NOT NULL,
    userId INTEGER NOT NULL,
    CONSTRAINT fk_userId FOREIGN KEY (userId) REFERENCES users(id),
    posts_id INTEGER NOT NULL,
    CONSTRAINT fk_postId FOREIGN KEY (posts_id) REFERENCES posts(id) 
);
CREATE TABLE comments (
    id INTEGER PRIMARY KEY ,
    content_comments TEXT NOT NULL ,
    userId INTEGER NOT NULL,
    CONSTRAINT fk_userId FOREIGN KEY (userId) REFERENCES users(id),
     created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
     posts_id INTEGER NOT NULL ,
    CONSTRAINT fk_postId FOREIGN KEY (posts_id) REFERENCES posts(id) 
);
COMMIT;
